# Generated by Django 6.1.1 on 2026-09-23 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lecture_number', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('lecture_date', models.DateField()),
                ('lecture_type', models.CharField(choices=[('recorded', 'Recorded Lecture'), ('live', 'Live Lecture')], default='recorded', max_length=20)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('notes', models.FileField(blank=True, null=True, upload_to='lecture_notes/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='website.course')),
            ],
            options={
                'ordering': ['lecture_number', 'lecture_date'],
            },
        ),
    ]
