# Generated by Django 6.1.1 on 2026-09-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_assignmentsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='submission_file',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_image',
            field=models.ImageField(blank=True, null=True, upload_to='assignment_submissions/images/'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_video',
            field=models.FileField(blank=True, null=True, upload_to='assignment_submissions/videos/'),
        ),
    ]
