# Generated by Django 6.1.1 on 2026-09-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_assignmentsubmission_submission_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
